<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Fitz.Seeds</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fitz.Database\Fitz.Database.csproj" />
    <ProjectReference Include="..\Fitz\Fitz.csproj" />
  </ItemGroup>

</Project>
