name: build-and-push-docker-image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
    GITHUB_REGISTRY: ghcr.io
    DOCKER_IMAGE: ${{ github.repository }}
    DOCKER_BUILDKIT: 1
    DOCKER_CLI_AGGREGATE: 1

jobs:
    build-push-docker-image:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: checkout the repo
              uses: actions/checkout@v4
            - name: login to ghcr.io
              run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u ${{ github.actor }} --password-stdin ${{ env.GITHUB_REGISTRY }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: build and push docker image using buildx
              run: |
                docker buildx create --use
                docker buildx inspect
                cd Fitz/
                docker buildx build \
                --platform linux/arm64,linux/amd64 \
                -t ${{ env.GITHUB_REGISTRY }}/${{ github.repository_owner }}/fitz:${{ github.sha }} \
                -f Dockerfile \
                --push .